#!/usr/bin/env bash
# The verification gate — run inside a feature worktree. Runs every applicable
# check and captures "one-look" evidence to EVIDENCE.md:
#
#   - always:            node test/run.js   (units + static load-time guards)
#   - if apps-script:    node --check       (paste-safety for the Apps Script file)
#   - if frontend:       playwright test    (REAL browser drives the feature)
#   - if supabase:       test/live          (the REAL Edge Function over HTTP —
#                                           skips itself when no backend is up)
#
# Exits non-zero if any check fails, so it doubles as a pre-push gate.
#
#   scripts/verify.sh [slug]   (slug defaults to the branch's last path segment)
set -uo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"
slug="${1:-$(git rev-parse --abbrev-ref HEAD | sed 's#.*/##')}"
base="${VERIFY_BASE:-master}"
EV="EVIDENCE.md"

# Everything different from the base branch (committed + working tree).
changed="$(git diff --name-only "$base" 2>/dev/null || true)"
is_fe=0; is_be=0; is_db=0
echo "$changed" | grep -qE '^(js/|index\.html|styles\.css)' && is_fe=1
echo "$changed" | grep -qE '^apps-script-Code\.gs' && is_be=1
echo "$changed" | grep -qE '^(supabase/|test/live/)' && is_db=1

pass=1

{
  echo "# Evidence — ${slug}"
  echo
  echo "_Generated by \`scripts/verify.sh\`. Base: \`${base}\`._"
  echo
  echo "## Changed files"
  echo '```'
  git diff --stat "$base" 2>/dev/null || true
  echo '```'
  echo
  echo "## node test/run.js — units + static guards"
  echo '```'
} > "$EV"
if node test/run.js >> "$EV" 2>&1; then :; else pass=0; fi
echo '```' >> "$EV"

if [ "$is_be" = 1 ]; then
  {
    echo
    echo "## node --check apps-script-Code.gs — paste-safety"
    echo '```'
  } >> "$EV"
  cp apps-script-Code.gs .verify-appsscript.js
  if node --check .verify-appsscript.js >> "$EV" 2>&1; then
    echo "OK: apps-script-Code.gs parses cleanly" >> "$EV"
  else
    pass=0
  fi
  rm -f .verify-appsscript.js
  echo '```' >> "$EV"
fi

if [ "$is_db" = 1 ]; then
  # Talks to a REAL Postgres + the REAL Edge Function. Skips itself (exit 0,
  # with a note in the evidence) when no backend is reachable, so this gate is
  # safe in CI while still being the thing that has to pass before cutover.
  {
    echo
    echo "## test/live — the real Edge Function over HTTP"
    echo '```'
  } >> "$EV"
  if node test/live/api-contract.test.js >> "$EV" 2>&1; then :; else pass=0; fi
  echo '```' >> "$EV"
fi

if [ "$is_fe" = 1 ]; then
  # Chromium needs libnspr4 / libnss3 / libasound2, which are not installed
  # system-wide on a machine without root. dev-env.sh's no-sudo toolchain keeps
  # them unpacked under ~/.local/pw-libs (DEV-ENV.md); point the loader at them
  # when they are there. A no-op everywhere else, CI included.
  PW_LIBS="$HOME/.local/pw-libs/root/usr/lib/x86_64-linux-gnu"
  [ -d "$PW_LIBS" ] && export LD_LIBRARY_PATH="$PW_LIBS:${LD_LIBRARY_PATH:-}"
  {
    echo
    echo "## Playwright — real-browser e2e (seeded demo data, no network)"
    echo '```'
  } >> "$EV"
  if npx playwright test >> "$EV" 2>&1; then :; else pass=0; fi
  echo '```' >> "$EV"
  echo >> "$EV"
  echo "Screenshots captured under \`test-results/\`." >> "$EV"
fi

{
  echo
  echo "## Manual test in the website"
  echo "\`\`\`"
  echo "bash scripts/preview.sh ${slug} 8080   # then open the printed URL"
  echo "\`\`\`"
  echo
  if [ "$pass" = 1 ]; then echo "## Result: ✅ PASS"; else echo "## Result: ❌ FAIL"; fi
} >> "$EV"

echo
cat "$EV"
[ "$pass" = 1 ]
