#!/usr/bin/env bash
# The verification gate — run inside a feature worktree. Runs every applicable
# check and captures "one-look" evidence to EVIDENCE.md:
#
#   - always:            node test/run.js   (units + static load-time guards)
#   - if apps-script:    node --check       (paste-safety for the Apps Script file)
#   - if frontend:       playwright test    (REAL browser drives the feature)
#
# Exits non-zero if any check fails, so it doubles as a pre-push gate.
#
#   scripts/verify.sh [slug]   (slug defaults to the branch's last path segment)
set -uo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"
slug="${1:-$(git rev-parse --abbrev-ref HEAD | sed 's#.*/##')}"
base="${VERIFY_BASE:-master}"
EV="EVIDENCE.md"

# Everything different from the base branch (committed + working tree).
changed="$(git diff --name-only "$base" 2>/dev/null || true)"
is_fe=0; is_be=0
echo "$changed" | grep -qE '^(js/|index\.html|styles\.css)' && is_fe=1
echo "$changed" | grep -qE '^apps-script-Code\.gs' && is_be=1

pass=1

{
  echo "# Evidence — ${slug}"
  echo
  echo "_Generated by \`scripts/verify.sh\`. Base: \`${base}\`._"
  echo
  echo "## Changed files"
  echo '```'
  git diff --stat "$base" 2>/dev/null || true
  echo '```'
  echo
  echo "## node test/run.js — units + static guards"
  echo '```'
} > "$EV"
if node test/run.js >> "$EV" 2>&1; then :; else pass=0; fi
echo '```' >> "$EV"

if [ "$is_be" = 1 ]; then
  {
    echo
    echo "## node --check apps-script-Code.gs — paste-safety"
    echo '```'
  } >> "$EV"
  cp apps-script-Code.gs .verify-appsscript.js
  if node --check .verify-appsscript.js >> "$EV" 2>&1; then
    echo "OK: apps-script-Code.gs parses cleanly" >> "$EV"
  else
    pass=0
  fi
  rm -f .verify-appsscript.js
  echo '```' >> "$EV"
fi

if [ "$is_fe" = 1 ]; then
  {
    echo
    echo "## Playwright — real-browser e2e (seeded demo data, no network)"
    echo '```'
  } >> "$EV"
  if npx playwright test >> "$EV" 2>&1; then :; else pass=0; fi
  echo '```' >> "$EV"
  echo >> "$EV"
  echo "Screenshots captured under \`test-results/\`." >> "$EV"
fi

{
  echo
  echo "## Manual test in the website"
  echo "\`\`\`"
  echo "bash scripts/preview.sh ${slug} 8080   # then open the printed URL"
  echo "\`\`\`"
  echo
  if [ "$pass" = 1 ]; then echo "## Result: ✅ PASS"; else echo "## Result: ❌ FAIL"; fi
} >> "$EV"

echo
cat "$EV"
[ "$pass" = 1 ]
